**Natural Language Pipeline and Text Processing**

![image.png](https://media.geeksforgeeks.org/wp-content/uploads/20250709120503764925/Text-Processing-21.webp)

**Data Collection**

In [15]:
#install google play scrapper
#pip install google-play-scraper

In [16]:
#import library
from google_play_scraper import reviews, Sort
import pandas as pd

In [17]:
result, continuation_token = reviews(
    'jp.konami.pesam',   # ganti dengan app id
    lang='en',              # ganti dengan bahasa
    # country='id',           # ganti dengan negara
    sort=Sort.NEWEST,       # review terbaru
    count=100              # jumlah review
)

In [18]:
#ubah jadi bentuk dataframe
result_df = pd.DataFrame(result)
result_df

,reviewId,userName,userImage,content,score,thumbsUpCount,reviewCreatedVersion,at,replyContent,repliedAt,appVersion
0,764d8c7d-3e51-4eb2-b52e-a83db2df6637,Isaac Dayo,https://play-lh.googleusercontent.com/a/ACg8ocKeRbjEUfIuS7GO2wk7WKR7t_bmJgK_9qOfk6DYF_k_L6ouog=mo,"every time there is one problem with this game why?, why do you guys interfere with the games, you favour a particular team over the other every single game, a lot of people are experiencing this, deny all you want it's true!, if you claim it isn't the management then definitely there is something wrong with your system, favoritism on a whole new level, defenders making mistakes, slow passes from midfielders, slow run from high pace strikers, BASICALLY THRASH, I am on the receiving end, FIX IT!",1,0,10.3.0,2026-03-01 09:29:04,None,None,10.3.0
1,8e5a0056-cf68-4b94-bbd8-a7b030cea240,Seif Junior,https://play-lh.googleusercontent.com/a/ACg8ocI3f2WpgX0FpAbrRRLkf7TiqXO08KohIOGqiUC0_clRpXFiJw=mo,Konami is the best the football game ever is efootball,5,0,10.3.0,2026-03-01 09:22:29,None,None,10.3.0
2,c1785a8e-cd63-4eaf-a55b-52a2d950de2a,Usman Shuaibu,https://play-lh.googleusercontent.com/a/ACg8ocLE5yuVbF53fuqvc2JvSMY9EUswDwGENwC_RmZENQusUryfFQ=mo,Uman,2,0,None,2026-03-01 09:20:39,None,None,None
3,f5dce206-a08a-485c-843e-85f264427257,Blessing Blaise Ofori Attah,https://play-lh.googleusercontent.com/a/ACg8ocIowbGUgfn2hzw1IcpjidPL93V1izrMEukF57s2pNOrbQvynQ=mo,I love this game but Konami please in your next update make sure you make it possible to transfer players from different account to another. If it is added l would able to make your review 5 stars,4,4,10.3.0,2026-03-01 09:18:28,None,None,10.3.0
4,85399cce-3c7e-4342-ae70-29d1ac67ed39,sanjay jay,https://play-lh.googleusercontent.com/a-/ALV-UjVAfoTKf8wFqwphm0bvvSc0N5TFjbkFJwvJeY7FnrTfpDQLQvZRBw,pes 2022?,4,0,10.3.0,2026-03-01 08:53:09,None,None,10.3.0
...,...,...,...,...,...,...,...,...,...,...,...
95,d1abe1ea-fffe-4bb6-903d-6a2515315cd7,Stephen Laryea,https://play-lh.googleusercontent.com/a-/ALV-UjX2fM7XBrF5SnsBQ-s5_WXlcyixxJjueEnvHyjn7Fs4543_uxA,Good game,5,0,10.3.0,2026-03-01 03:46:09,None,None,10.3.0
96,d6d71d59-1635-4fa8-8e34-903934e82c2d,Qudri Ose,https://play-lh.googleusercontent.com/a-/ALV-UjVvEMJH5Y4DqCxzE81EYd0E-P1JVdm_OEst7LDI5l-AF1xVhQ,Small,5,0,10.3.0,2026-03-01 03:40:26,None,None,10.3.0
97,d5381d7f-c2b1-43ed-81c0-5d2af35d82a5,Mary Nwamutalu,https://play-lh.googleusercontent.com/a/ACg8ocKhn1dzbtnvvHfIOsjHiGm4algq7PcstNwJm9TF_oiMMsJKNQ=mo,the game is good but make una put server for Nigeria,5,0,10.3.0,2026-03-01 03:39:18,None,None,10.3.0
98,6d46e03a-4ebc-4925-979e-70bbefef28bd,Whatsapp Encoding,https://play-lh.googleusercontent.com/a-/ALV-UjUO2vIvHvdx9ZnGciBtnLHgS8eI_emtP0Tqv3pxSD3eutL4QJE,The game is good but I think if their put something like champions league and other competition it will make it more fun to play,4,0,None,2026-03-01 03:38:43,None,None,None
99,b8d04d42-56a9-472e-8861-a0434988ef88,James God'swill,https://play-lh.googleusercontent.com/a-/ALV-UjW6nYcfPnthob17W5j87nlnT6OCDWeQa6ee3UNWLqhzqwvCXRgu,"e football is a very fantabulous game ,and i really enjoy playing the game "" am 💯 sure that e football is the best football game I have ever played.",5,0,10.3.0,2026-03-01 03:36:51,None,None,10.3.0

In [19]:
df = result_df.copy()
df

,reviewId,userName,userImage,content,score,thumbsUpCount,reviewCreatedVersion,at,replyContent,repliedAt,appVersion
0,764d8c7d-3e51-4eb2-b52e-a83db2df6637,Isaac Dayo,https://play-lh.googleusercontent.com/a/ACg8ocKeRbjEUfIuS7GO2wk7WKR7t_bmJgK_9qOfk6DYF_k_L6ouog=mo,"every time there is one problem with this game why?, why do you guys interfere with the games, you favour a particular team over the other every single game, a lot of people are experiencing this, deny all you want it's true!, if you claim it isn't the management then definitely there is something wrong with your system, favoritism on a whole new level, defenders making mistakes, slow passes from midfielders, slow run from high pace strikers, BASICALLY THRASH, I am on the receiving end, FIX IT!",1,0,10.3.0,2026-03-01 09:29:04,None,None,10.3.0
1,8e5a0056-cf68-4b94-bbd8-a7b030cea240,Seif Junior,https://play-lh.googleusercontent.com/a/ACg8ocI3f2WpgX0FpAbrRRLkf7TiqXO08KohIOGqiUC0_clRpXFiJw=mo,Konami is the best the football game ever is efootball,5,0,10.3.0,2026-03-01 09:22:29,None,None,10.3.0
2,c1785a8e-cd63-4eaf-a55b-52a2d950de2a,Usman Shuaibu,https://play-lh.googleusercontent.com/a/ACg8ocLE5yuVbF53fuqvc2JvSMY9EUswDwGENwC_RmZENQusUryfFQ=mo,Uman,2,0,None,2026-03-01 09:20:39,None,None,None
3,f5dce206-a08a-485c-843e-85f264427257,Blessing Blaise Ofori Attah,https://play-lh.googleusercontent.com/a/ACg8ocIowbGUgfn2hzw1IcpjidPL93V1izrMEukF57s2pNOrbQvynQ=mo,I love this game but Konami please in your next update make sure you make it possible to transfer players from different account to another. If it is added l would able to make your review 5 stars,4,4,10.3.0,2026-03-01 09:18:28,None,None,10.3.0
4,85399cce-3c7e-4342-ae70-29d1ac67ed39,sanjay jay,https://play-lh.googleusercontent.com/a-/ALV-UjVAfoTKf8wFqwphm0bvvSc0N5TFjbkFJwvJeY7FnrTfpDQLQvZRBw,pes 2022?,4,0,10.3.0,2026-03-01 08:53:09,None,None,10.3.0
...,...,...,...,...,...,...,...,...,...,...,...
95,d1abe1ea-fffe-4bb6-903d-6a2515315cd7,Stephen Laryea,https://play-lh.googleusercontent.com/a-/ALV-UjX2fM7XBrF5SnsBQ-s5_WXlcyixxJjueEnvHyjn7Fs4543_uxA,Good game,5,0,10.3.0,2026-03-01 03:46:09,None,None,10.3.0
96,d6d71d59-1635-4fa8-8e34-903934e82c2d,Qudri Ose,https://play-lh.googleusercontent.com/a-/ALV-UjVvEMJH5Y4DqCxzE81EYd0E-P1JVdm_OEst7LDI5l-AF1xVhQ,Small,5,0,10.3.0,2026-03-01 03:40:26,None,None,10.3.0
97,d5381d7f-c2b1-43ed-81c0-5d2af35d82a5,Mary Nwamutalu,https://play-lh.googleusercontent.com/a/ACg8ocKhn1dzbtnvvHfIOsjHiGm4algq7PcstNwJm9TF_oiMMsJKNQ=mo,the game is good but make una put server for Nigeria,5,0,10.3.0,2026-03-01 03:39:18,None,None,10.3.0
98,6d46e03a-4ebc-4925-979e-70bbefef28bd,Whatsapp Encoding,https://play-lh.googleusercontent.com/a-/ALV-UjUO2vIvHvdx9ZnGciBtnLHgS8eI_emtP0Tqv3pxSD3eutL4QJE,The game is good but I think if their put something like champions league and other competition it will make it more fun to play,4,0,None,2026-03-01 03:38:43,None,None,None
99,b8d04d42-56a9-472e-8861-a0434988ef88,James God'swill,https://play-lh.googleusercontent.com/a-/ALV-UjW6nYcfPnthob17W5j87nlnT6OCDWeQa6ee3UNWLqhzqwvCXRgu,"e football is a very fantabulous game ,and i really enjoy playing the game "" am 💯 sure that e football is the best football game I have ever played.",5,0,10.3.0,2026-03-01 03:36:51,None,None,10.3.0

In [20]:
#set agar data bisa dilihat dengan lebar kolom maksimal
pd.set_option('display.max_colwidth', None)

In [21]:
#lihat kolom konten
df['content'].head(50)

0     every time there is one problem with this game why?, why do you guys interfere with the games, you favour a particular team over the other every single game, a lot of people are experiencing this, deny all you want it's true!, if you claim it isn't the management then definitely there is something wrong with your system, favoritism on a whole new level, defenders making mistakes, slow passes from midfielders, slow run from high pace strikers, BASICALLY THRASH, I am on the receiving end, FIX IT!
1                                                                                                                                                                                                                                                                                                                                                                                                                                                                  Konami is the best the football game ever is efootball
2                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    Uman
3                                                                                                                                                                                                                                                                                                                    I love this game but Konami please in your next update make sure you make it possible to transfer players from different account to another. If it is added l would able to make your review 5 stars
4                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               pes 2022?
5                                                                                                                                                                                                                                                                                                                                                                                                                                         babi konami. spin player tak pernah ada luck bangang betul. Very stupid konami.
6                                                                                                                                                                                                                                                                                                                                                                                                                                                                the substitutions is not seen as compared with Fc mobile
7                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               like thid
8                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        i love this game
9                                                                                                                                                                                                                                                                                                                                                                                                          The script is too much bro we're tired man you can do better please. the division is so manipulating bro 🤦‍♂️💔
10                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             Perfect best football game
11                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              best game
12                                                                                                                                                                                                                                                                                                            Give fede valverde his long socks. and for the next major update for the new season in August surprise us with new goal post nets. And by the way the game is top notch honestly 👌 my favorite i love it.❤️
13                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     the best game ever
14                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               optional
15                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   nice
16                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             efootball is the best game
17                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 Nice 😀
18                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   wow!
19                                                                                                                                                                                                                                                                                                                                                                                                                     Its a good game but they should give us more opertonities to gather more coins and valuable awards
20                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     😊😊
21                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            لعبة ممتازة
22                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             great game
23                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   nice
24                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     words won't explain this good game
25                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              very good
26                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   good
27                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   Best
28                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       when there is Neymar there's fun
29                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  best game of the year
30                                                                                                                                                                                                                                                                                       see am a person of truth the person that invented this game is a bastard you shall never perish because tell me the reason ai division match I can score keeper of 99 an AI will score my keeper of 104 you people are a bastard
31                                                                                                                                                                                                                                                                                                                               wow this is one of the beutiful game that I have seen before, you even looked at the graphics how they smile and look at Messi and Neymar wow it's a good and nice graphics for the game
32                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    nic
33                                                                                                                                                                                                                                    I’ve never seen such a terrible game like this in my life. The scripting never ends. Those who spend money in the game get much better gameplay. I’ve never seen a game with this much scripting. They give more priority to players who spend money. Normal players have no value.
34                                                                                                                                                                                                                                                                                                                                                                                                                                                          app is marvelous...😂 work on improving the cursor sensitivity
35                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         eFotball Farnk
36                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                no comment to scribet 🤬
37                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      after codm na you
38                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              Good game

In [22]:
#masukan kolom content ke dalam variabel baru
data_cleaning = df['content']
data_cleaning.head(30)

0     every time there is one problem with this game why?, why do you guys interfere with the games, you favour a particular team over the other every single game, a lot of people are experiencing this, deny all you want it's true!, if you claim it isn't the management then definitely there is something wrong with your system, favoritism on a whole new level, defenders making mistakes, slow passes from midfielders, slow run from high pace strikers, BASICALLY THRASH, I am on the receiving end, FIX IT!
1                                                                                                                                                                                                                                                                                                                                                                                                                                                                  Konami is the best the football game ever is efootball
2                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    Uman
3                                                                                                                                                                                                                                                                                                                    I love this game but Konami please in your next update make sure you make it possible to transfer players from different account to another. If it is added l would able to make your review 5 stars
4                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               pes 2022?
5                                                                                                                                                                                                                                                                                                                                                                                                                                         babi konami. spin player tak pernah ada luck bangang betul. Very stupid konami.
6                                                                                                                                                                                                                                                                                                                                                                                                                                                                the substitutions is not seen as compared with Fc mobile
7                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               like thid
8                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        i love this game
9                                                                                                                                                                                                                                                                                                                                                                                                          The script is too much bro we're tired man you can do better please. the division is so manipulating bro 🤦‍♂️💔
10                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             Perfect best football game
11                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              best game
12                                                                                                                                                                                                                                                                                                            Give fede valverde his long socks. and for the next major update for the new season in August surprise us with new goal post nets. And by the way the game is top notch honestly 👌 my favorite i love it.❤️
13                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     the best game ever
14                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               optional
15                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   nice
16                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             efootball is the best game
17                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 Nice 😀
18                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   wow!
19                                                                                                                                                                                                                                                                                                                                                                                                                     Its a good game but they should give us more opertonities to gather more coins and valuable awards
20                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     😊😊
21                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            لعبة ممتازة
22                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             great game
23                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   nice
24                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     words won't explain this good game
25                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              very good
26                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   good
27                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   Best
28                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       when there is Neymar there's fun
29                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  best game of the year
Name: content, dtype: object

**Lowercasing**

In [23]:
df['content_clean'] = df['content'].str.lower()
df['content_clean'].head(50)

0     every time there is one problem with this game why?, why do you guys interfere with the games, you favour a particular team over the other every single game, a lot of people are experiencing this, deny all you want it's true!, if you claim it isn't the management then definitely there is something wrong with your system, favoritism on a whole new level, defenders making mistakes, slow passes from midfielders, slow run from high pace strikers, basically thrash, i am on the receiving end, fix it!
1                                                                                                                                                                                                                                                                                                                                                                                                                                                                  konami is the best the football game ever is efootball
2                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    uman
3                                                                                                                                                                                                                                                                                                                    i love this game but konami please in your next update make sure you make it possible to transfer players from different account to another. if it is added l would able to make your review 5 stars
4                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               pes 2022?
5                                                                                                                                                                                                                                                                                                                                                                                                                                         babi konami. spin player tak pernah ada luck bangang betul. very stupid konami.
6                                                                                                                                                                                                                                                                                                                                                                                                                                                                the substitutions is not seen as compared with fc mobile
7                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               like thid
8                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        i love this game
9                                                                                                                                                                                                                                                                                                                                                                                                          the script is too much bro we're tired man you can do better please. the division is so manipulating bro 🤦‍♂️💔
10                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             perfect best football game
11                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              best game
12                                                                                                                                                                                                                                                                                                            give fede valverde his long socks. and for the next major update for the new season in august surprise us with new goal post nets. and by the way the game is top notch honestly 👌 my favorite i love it.❤️
13                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     the best game ever
14                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               optional
15                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   nice
16                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             efootball is the best game
17                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 nice 😀
18                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   wow!
19                                                                                                                                                                                                                                                                                                                                                                                                                     its a good game but they should give us more opertonities to gather more coins and valuable awards
20                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     😊😊
21                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            لعبة ممتازة
22                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             great game
23                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   nice
24                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     words won't explain this good game
25                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              very good
26                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   good
27                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   best
28                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       when there is neymar there's fun
29                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  best game of the year
30                                                                                                                                                                                                                                                                                       see am a person of truth the person that invented this game is a bastard you shall never perish because tell me the reason ai division match i can score keeper of 99 an ai will score my keeper of 104 you people are a bastard
31                                                                                                                                                                                                                                                                                                                               wow this is one of the beutiful game that i have seen before, you even looked at the graphics how they smile and look at messi and neymar wow it's a good and nice graphics for the game
32                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    nic
33                                                                                                                                                                                                                                    i’ve never seen such a terrible game like this in my life. the scripting never ends. those who spend money in the game get much better gameplay. i’ve never seen a game with this much scripting. they give more priority to players who spend money. normal players have no value.
34                                                                                                                                                                                                                                                                                                                                                                                                                                                          app is marvelous...😂 work on improving the cursor sensitivity
35                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         efotball farnk
36                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                no comment to scribet 🤬
37                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      after codm na you
38                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              good game

In [ ]:
df['content_clean'].str.replace('[^\w\s]','',regex=True).head(50) 
# regex untuk menghapus tanda baca, simbol, dan karakter khusus lainnya. w untuk menghapus karakter non-kata, s untuk menghapus karakter spasi, dan ^ untuk negasi. Jadi, [^\w\s] berarti "hapus semua karakter yang bukan kata atau spasi".

<>:1: SyntaxWarning: invalid escape sequence '\w'
<>:1: SyntaxWarning: invalid escape sequence '\w'
C:\Users\USER\AppData\Local\Temp\ipykernel_20272\4156829393.py:1: SyntaxWarning: invalid escape sequence '\w'
  df['content_clean'].str.replace('[^\w\s]','',regex=True).head(50)

0     every time there is one problem with this game why why do you guys interfere with the games you favour a particular team over the other every single game a lot of people are experiencing this deny all you want its true if you claim it isnt the management then definitely there is something wrong with your system favoritism on a whole new level defenders making mistakes slow passes from midfielders slow run from high pace strikers basically thrash i am on the receiving end fix it
1                                                                                                                                                                                                                                                                                                                                                                                                                                                 konami is the best the football game ever is efootball
2                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   uman
3                                                                                                                                                                                                                                                                                                    i love this game but konami please in your next update make sure you make it possible to transfer players from different account to another if it is added l would able to make your review 5 stars
4                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               pes 2022
5                                                                                                                                                                                                                                                                                                                                                                                                                           babi konami spin player tak pernah ada luck bangang betul very stupid konami
6                                                                                                                                                                                                                                                                                                                                                                                                                                               the substitutions is not seen as compared with fc mobile
7                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              like thid
8                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       i love this game
9                                                                                                                                                                                                                                                                                                                                                                                                the script is too much bro were tired man you can do better please the division is so manipulating bro
10                                                                                                                                                                                                                                                                                                                                                                                                                                                                            perfect best football game
11                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             best game
12                                                                                                                                                                                                                                                                                                 give fede valverde his long socks and for the next major update for the new season in august surprise us with new goal post nets and by the way the game is top notch honestly  my favorite i love it
13                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    the best game ever
14                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              optional
15                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  nice
16                                                                                                                                                                                                                                                                                                                                                                                                                                                                            efootball is the best game
17                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 nice
18                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   wow
19                                                                                                                                                                                                                                                                                                                                                                                                    its a good game but they should give us more opertonities to gather more coins and valuable awards
20
21                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           لعبة ممتازة
22                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            great game
23                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  nice
24                                                                                                                                                                                                                                                                                                                                                                                                                                                                     words wont explain this good game
25                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             very good
26                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  good
27                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  best
28                                                                                                                                                                                                                                                                                                                                                                                                                                                                       when there is neymar theres fun
29                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 best game of the year
30                                                                                                                                                                                                                                                                      see am a person of truth the person that invented this game is a bastard you shall never perish because tell me the reason ai division match i can score keeper of 99 an ai will score my keeper of 104 you people are a bastard
31                                                                                                                                                                                                                                                                                                                wow this is one of the beutiful game that i have seen before you even looked at the graphics how they smile and look at messi and neymar wow its a good and nice graphics for the game
32                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   nic
33                                                                                                                                                                                                                           ive never seen such a terrible game like this in my life the scripting never ends those who spend money in the game get much better gameplay ive never seen a game with this much scripting they give more priority to players who spend money normal players have no value
34                                                                                                                                                                                                                                                                                                                                                                                                                                             app is marvelous work on improving the cursor sensitivity
35                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        efotball farnk
36                                                                                                                                                                                                                                                                                                                                                                                                                                                                                no comment to scribet
37                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     after codm na you
38                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             good game
39         it is impossible to ignore the scripting in this game whenever i am just one point or one win away from division 1 the game completely manipulates the match my players suddenly become heavy and unresponsive they cant pass cant shoot and lose every ball to make it worse the lag magically appears only when im inside the opponents box its pathetic that i lose to a 2000rated team just because the game decided i shouldnt win this isnt a football simulation its a programmed scam
40                                                                                                                                                                                                                                                                                                                                                                                                                                                                           the best football game ever

**Remove Punctuation**

In [25]:
df['content_clean'].str.replace('[^\w\s]','',regex=True)

<>:1: SyntaxWarning: invalid escape sequence '\w'
<>:1: SyntaxWarning: invalid escape sequence '\w'
C:\Users\USER\AppData\Local\Temp\ipykernel_20272\3208373244.py:1: SyntaxWarning: invalid escape sequence '\w'
  df['content_clean'].str.replace('[^\w\s]','',regex=True)

0     every time there is one problem with this game why why do you guys interfere with the games you favour a particular team over the other every single game a lot of people are experiencing this deny all you want its true if you claim it isnt the management then definitely there is something wrong with your system favoritism on a whole new level defenders making mistakes slow passes from midfielders slow run from high pace strikers basically thrash i am on the receiving end fix it
1                                                                                                                                                                                                                                                                                                                                                                                                                                                 konami is the best the football game ever is efootball
2                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   uman
3                                                                                                                                                                                                                                                                                                    i love this game but konami please in your next update make sure you make it possible to transfer players from different account to another if it is added l would able to make your review 5 stars
4                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               pes 2022
                                                                                                                                                                                                                                                     ...
95                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             good game
96                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 small
97                                                                                                                                                                                                                                                                                                                                                                                                                                                  the game is good but make una put server for nigeria
98                                                                                                                                                                                                                                                                                                                                                                      the game is good but i think if their put something like champions league and other competition it will make it more fun to play
99                                                                                                                                                                                                                                                                                                                                                      e football is a very fantabulous game and i really enjoy playing the game  am  sure that e football is the best football game i have ever played
Name: content_clean, Length: 100, dtype: object

**Masukan ke dalam satu fungsi**

In [26]:
def clean_data(text,column_name):
    df['content_clean'] = df[column_name].str.lower()
    df['content_clean'] = df['content_clean'].str.replace('[^\w\s]','',regex=True)
    return df

<>:3: SyntaxWarning: invalid escape sequence '\w'
<>:3: SyntaxWarning: invalid escape sequence '\w'
C:\Users\USER\AppData\Local\Temp\ipykernel_20272\1186799193.py:3: SyntaxWarning: invalid escape sequence '\w'
  df['content_clean'] = df['content_clean'].str.replace('[^\w\s]','',regex=True)

In [27]:
df = clean_data(df, 'content')

print(df[['content', 'content_clean']])

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                content  \
0   every time there is one problem with this game why?, why do you guys interfere with the games, you favour a particular team over the other every single game, a lot of people are experiencing this, deny all you want it's true!, if you claim it isn't the management then definitely there is something wrong with your system, favoritism on a whole new level, defenders making mistakes, slow passes from midfielders, slow run from high pace strikers, BASICALLY THRASH, I am on the receiving end, FIX IT!
1                                                                                                                                                                                                                                                                                                                                                                                                                                                                Konami is the best the football game ever is efootball
2                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  Uman
3                                                                                                                                                                                                                                                                                                                  I love this game but Konami please in your next update make sure you make it possible to transfer players from different account to another. If it is added l would able to make your review 5 stars
4                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             pes 2022?
..                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  ...
95                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            Good game
96                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                Small
97                                                                                                                                                                                                                                                                                                                                                                                                                                                                 the game is good but make una put server for Nigeria
98                                                                                                                                                                                                                                                                                                                                                                                     The game is good but I think if their put something like champions league and other competition it will make it more fun to play
99                                                                                                                                                                                                                                                                                                                                                                 e football is a very fantabulous game ,and i really enjoy playing the game " am 💯 sure that e football is the best football game I have ever played.

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         content_clean
0   every time there is one problem with this game why why do you guys interfere with the games you favour a particular team over the other every single game a lot of people are experiencing this deny all you want its true if you claim it isnt the management then definitely there is something wrong with your system favoritism on a whole new level defenders making mistakes slow passes from midfielders slow run from high pace strikers basically thrash i am on the receiving end fix it
1                                                                                                                                                                                                                                                                                                                                                                                                                                               konami is the best the football game ever is efootball
2                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 uman
3                                                                                                                                                                                                                                                                                                  i love this game but konami please in your next update make sure you make it possible to transfer players from different account to another if it is added l would able to make your review 5 stars
4                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             pes 2022
..                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 ...
95                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           good game
96                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               small
97                                                                                                                                                                                                                                                                                                                                                                                                                                                the game is good but make una put server for nigeria
98                                                                                                                                                                                                                                                                                                                                                                    the game is good but i think if their put something like champions league and other competition it will make it more fun to play
99                                                                                                                                                                                                                                                                                                                                                    e football is a very fantabulous game and i really enjoy playing the game  am  sure that e football is the best football game i have ever played

[100 rows x 2 columns]

**Penggunaan library Spacy untuk text processing**

In [28]:
#import library spacy
import spacy

In [35]:
#load model spacy untuk text processing
nlp = spacy.load('en_core_web_sm')
phrase = df.loc[1, 'content_clean']
phrase

'konami is the best the football game ever is efootball'

In [36]:
doc = nlp(phrase)
doc

konami is the best the football game ever is efootball

**Tokenization**

In [37]:
[token for token in doc]

[konami, is, the, best, the, football, game, ever, is, efootball]

**Lemmatization**

In [ ]:
[token.lemma_ for token in doc if not token.is_stop] # menghapus stopword dan melakukan lemmatization pada kata-kata dalam frase.

['konami', 'good', 'football', 'game', 'efootball']

**Stop Word**

In [39]:
list(nlp.Defaults.stop_words)[:10]

['not',
 'namely',
 'once',
 'someone',
 'their',
 "'ve",
 'fifty',
 'were',
 'since',
 'without']