**Natural Language Pipeline and Text Processing**

![image.png](https://media.geeksforgeeks.org/wp-content/uploads/20250709120503764925/Text-Processing-21.webp)

**Data Collection**

In [1]:
#install google play scrapper
#pip install google-play-scraper

In [2]:
#import library
from google_play_scraper import reviews, Sort
import pandas as pd

In [3]:
result, continuation_token = reviews(
    'com.mobile.legends',   # ganti dengan app id
    lang='en',              # ganti dengan bahasa
    # country='id',           # ganti dengan negara
    sort=Sort.NEWEST,       # review terbaru
    count=100              # jumlah review
)

In [4]:
#ubah jadi bentuk dataframe
result_df = pd.DataFrame(result)
result_df

,reviewId,userName,userImage,content,score,thumbsUpCount,reviewCreatedVersion,at,replyContent,repliedAt,appVersion
0,568f7b54-cbf5-488c-a06c-0df9daee01b2,Nilo Recto,https://play-lh.googleusercontent.com/a-/ALV-U...,Ano na moonton ayos ayos in Mona mga matching ...,1,0,2.1.49.11493,2026-03-01 10:03:30,None,None,2.1.49.11493
1,65ba2393-dff8-4ca1-873d-493bd44bf20f,Lawrence,https://play-lh.googleusercontent.com/a/ACg8oc...,"ugly match making, rather unfair match making",1,0,None,2026-03-01 10:03:04,None,None,None
2,44f12a86-e357-4bfa-b3e1-d92514e0a048,Su ZAN Raii,https://play-lh.googleusercontent.com/a/ACg8oc...,niceeee game but need to bring back my old Han...,1,0,2.1.47.11491,2026-03-01 09:59:42,None,None,2.1.47.11491
3,afedff38-4a59-4566-b179-943320eeecc6,Johnlloyd Formentera,https://play-lh.googleusercontent.com/a/ACg8oc...,"if you play solo, your teammates is trio or du...",1,0,2.1.31.11233,2026-03-01 09:59:27,None,None,2.1.31.11233
4,64542346-5e0e-4580-b1df-0fb46d310b19,Joyce Anne Braza Gulinao,https://play-lh.googleusercontent.com/a-/ALV-U...,Moonton must fix match making because when you...,1,0,2.1.47.11491,2026-03-01 09:59:25,None,None,2.1.47.11491
...,...,...,...,...,...,...,...,...,...,...,...
95,4f12a3d9-59c6-4b87-8f99-bcfceb95afb7,xevious ren,https://play-lh.googleusercontent.com/a-/ALV-U...,Perfect experience!. well even tho sometimes t...,5,0,2.1.41.11465,2026-03-01 05:35:58,None,None,2.1.41.11465
96,6562a90b-3f05-4adb-8540-7f8df154b591,KirbyJohn Tude,https://play-lh.googleusercontent.com/a-/ALV-U...,bring back the old mayhem its sooo boring nowa...,1,0,2.1.47.11491,2026-03-01 05:30:37,None,None,2.1.47.11491
97,bfc243f7-338d-45ea-86fd-c0a4e17d2f83,kevin stiven muñoz molina,https://play-lh.googleusercontent.com/a-/ALV-U...,"cada año el juego empeora mas , los emparejami...",3,0,1.8.8.8811,2026-03-01 05:27:40,None,None,1.8.8.8811
98,30645483-c098-43ac-bf05-9ad215804023,Ezekiel Estacio,https://play-lh.googleusercontent.com/a/ACg8oc...,they change my id version now i cant play with...,1,0,2.1.47.11491,2026-03-01 05:22:57,None,None,2.1.47.11491
99,dd7fc518-b531-446c-9ac6-a27818256558,Jake Dapusala,https://play-lh.googleusercontent.com/a/ACg8oc...,best game,5,0,2.1.49.11493,2026-03-01 05:15:29,None,None,2.1.49.11493

In [5]:
df = result_df.copy()
df

,reviewId,userName,userImage,content,score,thumbsUpCount,reviewCreatedVersion,at,replyContent,repliedAt,appVersion
0,568f7b54-cbf5-488c-a06c-0df9daee01b2,Nilo Recto,https://play-lh.googleusercontent.com/a-/ALV-U...,Ano na moonton ayos ayos in Mona mga matching ...,1,0,2.1.49.11493,2026-03-01 10:03:30,None,None,2.1.49.11493
1,65ba2393-dff8-4ca1-873d-493bd44bf20f,Lawrence,https://play-lh.googleusercontent.com/a/ACg8oc...,"ugly match making, rather unfair match making",1,0,None,2026-03-01 10:03:04,None,None,None
2,44f12a86-e357-4bfa-b3e1-d92514e0a048,Su ZAN Raii,https://play-lh.googleusercontent.com/a/ACg8oc...,niceeee game but need to bring back my old Han...,1,0,2.1.47.11491,2026-03-01 09:59:42,None,None,2.1.47.11491
3,afedff38-4a59-4566-b179-943320eeecc6,Johnlloyd Formentera,https://play-lh.googleusercontent.com/a/ACg8oc...,"if you play solo, your teammates is trio or du...",1,0,2.1.31.11233,2026-03-01 09:59:27,None,None,2.1.31.11233
4,64542346-5e0e-4580-b1df-0fb46d310b19,Joyce Anne Braza Gulinao,https://play-lh.googleusercontent.com/a-/ALV-U...,Moonton must fix match making because when you...,1,0,2.1.47.11491,2026-03-01 09:59:25,None,None,2.1.47.11491
...,...,...,...,...,...,...,...,...,...,...,...
95,4f12a3d9-59c6-4b87-8f99-bcfceb95afb7,xevious ren,https://play-lh.googleusercontent.com/a-/ALV-U...,Perfect experience!. well even tho sometimes t...,5,0,2.1.41.11465,2026-03-01 05:35:58,None,None,2.1.41.11465
96,6562a90b-3f05-4adb-8540-7f8df154b591,KirbyJohn Tude,https://play-lh.googleusercontent.com/a-/ALV-U...,bring back the old mayhem its sooo boring nowa...,1,0,2.1.47.11491,2026-03-01 05:30:37,None,None,2.1.47.11491
97,bfc243f7-338d-45ea-86fd-c0a4e17d2f83,kevin stiven muñoz molina,https://play-lh.googleusercontent.com/a-/ALV-U...,"cada año el juego empeora mas , los emparejami...",3,0,1.8.8.8811,2026-03-01 05:27:40,None,None,1.8.8.8811
98,30645483-c098-43ac-bf05-9ad215804023,Ezekiel Estacio,https://play-lh.googleusercontent.com/a/ACg8oc...,they change my id version now i cant play with...,1,0,2.1.47.11491,2026-03-01 05:22:57,None,None,2.1.47.11491
99,dd7fc518-b531-446c-9ac6-a27818256558,Jake Dapusala,https://play-lh.googleusercontent.com/a/ACg8oc...,best game,5,0,2.1.49.11493,2026-03-01 05:15:29,None,None,2.1.49.11493

In [6]:
#set agar data bisa dilihat dengan lebar kolom maksimal
pd.set_option('display.max_colwidth', None)

In [7]:
#lihat kolom konten
df['content'].head(50)

0                                                                                                                                                                                                                                                                                                                                                                                                                   Ano na moonton ayos ayos in Mona mga matching MO Kaya na lipat Yong mga player sa hok gawa macthing
1                                                                                                                                                                                                                                                                                                                                                                                                                                                                         ugly match making, rather unfair match making
2                        niceeee game but need to bring back my old Hanzo skill new wasn't comfortable🤐 for brain.😼🩹 too much bugs in game🏁 and too chares heating well pressure on game sir😔. need to balance🏳️ game ability roles plays heroes🫥😶‍🌫️ balanced counter heroes ability🌠. and frequency of MLBB challenges. and animes free events🥺for various like KOF HEROES NEED BRING SOME Unique more to have fun wit. 💊🦋🐾🎩💤💯🩹🌸🛡️😸. hacrr in games uncommon build of Miya and somes depressed heroes to me hit hard.
3                                                                                                                                                                                                                                                                                                                                                                                                                             if you play solo, your teammates is trio or duo. this game is so unfair for solo players!
4                                                                                                                                                                                                                                                                                                                                                                     Moonton must fix match making because when you lose 1 it's become lose streak and it's hard to win the game when you're at the dark system server
5                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     pretty to play 💗💗
6                                                                                                                                                                                                                                                                                                                                                                                                                             if you play solo, your teammates is trio or duo. this game is so unfair for solo players!
7                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          walang kwenta matching nyu..
8                                                                                                                                                                                                                                                                                                                                                                                                                                     so laggy like my wifi and my data have a strong network but still lag on the game
9                                                                                                                                                                                                                                                                                                                                                                        lose streak lagi ako tang Ina mo ml namatay kana tang Ina mo laro mo bolok tan Ina mo hayup ka Gago sintosinto tarantado namatay kana hayop ka
10                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    so good this game
11                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         Amazing game
12                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    I love this game🥰
13                                                                                                                                                                                                                                                                                                                                                                                                                                                                  stupid match making, always team up with stupid bot
14                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 best
15                                                                                                                                                                                                                                                                                                                                                                                                                   It has been my comfort zone whenever im bored and i also enjoy playing with my friends i love it!!
16                                                                                                                                                                                                                                                                                       my account got ban for no reason and I need it back is because Simultaneous match but I didn't play with same enemy or something and all people got banned because of that so I need it back please is important to my brother
17                                                                                                                                                                                                                                                                                                                                                                                                                                                                 DON'T REVAMPED LUO YI, HER SKIN IS ALREADY OKAY!!!!!
18                                                                                                                                                                                                                                                                                                                                                                                                                                                                           Constantly updating, even when in-game.👎👎👎
19                                                                                                                                                                                                                                                                                                                                                                                                      maganda naman, kaso pa legend ka na daming cancer ,may Tanga may bobo may isip bata tapos ng tri-trip. yon lang
20                                                                                                                                                                                                                                                                                                                                                                                                                                                                          this game is the best game ever of my phone
21                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 Good
22                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          game sampah
23                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         it is so fun
24                                                                                                                                                                                                                                                                                                                                                                       i'll make it 5 star if all the limited event skins will be for sale on every promo dias events, so that others who missed the event can buy it
25                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              ME W210
26                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               So fun
27                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 good
28                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   ok
29                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        AungThihakyaw
30                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             Good boy
31                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   greatest game ever
32                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              Diamond
33                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  gud
34                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           This the best game overall
35                                                                                                                                                                                                                                                                                                                                         woy moonton, klau ada yg ngelaporin player yang gameplaynya kyk bot please la di kasih sanksi bukann mlh lu proses" mulu kgaa ada sanksinya, pdhl jelas" gameplaynya kek bot
36                                                                                                                                                                                                                                                                                                                                                                                                                                                                               like the game pls ban hackers fix bugs
37    ts game is fun and all but there’s one thing i really hate and i hope you guys can fix it, it’s not about the dark system or bad teammates it's about playing solo i'm literally facing enemies who are teaming up together while i'm solo queueing like seriously that’s so unfair you guys should make solo players face other solo players not full teams, when they’re teamed up they already have plans and coordination so ofc they have an advantage so pls fix ts it really ruins the solo experience 😭🙏🥀
38                                                                                                                                                                                                                                                                            This game is really great and also makes me have fun when playing it. but I once won but I didn't get a star, why can this happen? explain.. I'm back. now I'm gonna say in Malay.Moonton kalau kasih lawan tak paya la juga Susah sangat

In [8]:
#masukan kolom content ke dalam variabel baru
data_cleaning = df['content']
data_cleaning.head(30)

0                                                                                                                                                                                                                                                                                                                                                                                                Ano na moonton ayos ayos in Mona mga matching MO Kaya na lipat Yong mga player sa hok gawa macthing
1                                                                                                                                                                                                                                                                                                                                                                                                                                                      ugly match making, rather unfair match making
2     niceeee game but need to bring back my old Hanzo skill new wasn't comfortable🤐 for brain.😼🩹 too much bugs in game🏁 and too chares heating well pressure on game sir😔. need to balance🏳️ game ability roles plays heroes🫥😶‍🌫️ balanced counter heroes ability🌠. and frequency of MLBB challenges. and animes free events🥺for various like KOF HEROES NEED BRING SOME Unique more to have fun wit. 💊🦋🐾🎩💤💯🩹🌸🛡️😸. hacrr in games uncommon build of Miya and somes depressed heroes to me hit hard.
3                                                                                                                                                                                                                                                                                                                                                                                                          if you play solo, your teammates is trio or duo. this game is so unfair for solo players!
4                                                                                                                                                                                                                                                                                                                                                  Moonton must fix match making because when you lose 1 it's become lose streak and it's hard to win the game when you're at the dark system server
5                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  pretty to play 💗💗
6                                                                                                                                                                                                                                                                                                                                                                                                          if you play solo, your teammates is trio or duo. this game is so unfair for solo players!
7                                                                                                                                                                                                                                                                                                                                                                                                                                                                       walang kwenta matching nyu..
8                                                                                                                                                                                                                                                                                                                                                                                                                  so laggy like my wifi and my data have a strong network but still lag on the game
9                                                                                                                                                                                                                                                                                                                                                     lose streak lagi ako tang Ina mo ml namatay kana tang Ina mo laro mo bolok tan Ina mo hayup ka Gago sintosinto tarantado namatay kana hayop ka
10                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 so good this game
11                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      Amazing game
12                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 I love this game🥰
13                                                                                                                                                                                                                                                                                                                                                                                                                                               stupid match making, always team up with stupid bot
14                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              best
15                                                                                                                                                                                                                                                                                                                                                                                                It has been my comfort zone whenever im bored and i also enjoy playing with my friends i love it!!
16                                                                                                                                                                                                                                                                    my account got ban for no reason and I need it back is because Simultaneous match but I didn't play with same enemy or something and all people got banned because of that so I need it back please is important to my brother
17                                                                                                                                                                                                                                                                                                                                                                                                                                              DON'T REVAMPED LUO YI, HER SKIN IS ALREADY OKAY!!!!!
18                                                                                                                                                                                                                                                                                                                                                                                                                                                        Constantly updating, even when in-game.👎👎👎
19                                                                                                                                                                                                                                                                                                                                                                                   maganda naman, kaso pa legend ka na daming cancer ,may Tanga may bobo may isip bata tapos ng tri-trip. yon lang
20                                                                                                                                                                                                                                                                                                                                                                                                                                                       this game is the best game ever of my phone
21                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              Good
22                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       game sampah
23                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      it is so fun
24                                                                                                                                                                                                                                                                                                                                                    i'll make it 5 star if all the limited event skins will be for sale on every promo dias events, so that others who missed the event can buy it
25                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           ME W210
26                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            So fun
27                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              good
28                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                ok
29                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     AungThihakyaw
Name: content, dtype: object

**Lowercasing**

In [9]:
df['content_clean'] = df['content'].str.lower()
df['content_clean'].head(50)

0                                                                                                                                                                                                                                                                                                                                                                                                                   ano na moonton ayos ayos in mona mga matching mo kaya na lipat yong mga player sa hok gawa macthing
1                                                                                                                                                                                                                                                                                                                                                                                                                                                                         ugly match making, rather unfair match making
2                        niceeee game but need to bring back my old hanzo skill new wasn't comfortable🤐 for brain.😼🩹 too much bugs in game🏁 and too chares heating well pressure on game sir😔. need to balance🏳️ game ability roles plays heroes🫥😶‍🌫️ balanced counter heroes ability🌠. and frequency of mlbb challenges. and animes free events🥺for various like kof heroes need bring some unique more to have fun wit. 💊🦋🐾🎩💤💯🩹🌸🛡️😸. hacrr in games uncommon build of miya and somes depressed heroes to me hit hard.
3                                                                                                                                                                                                                                                                                                                                                                                                                             if you play solo, your teammates is trio or duo. this game is so unfair for solo players!
4                                                                                                                                                                                                                                                                                                                                                                     moonton must fix match making because when you lose 1 it's become lose streak and it's hard to win the game when you're at the dark system server
5                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     pretty to play 💗💗
6                                                                                                                                                                                                                                                                                                                                                                                                                             if you play solo, your teammates is trio or duo. this game is so unfair for solo players!
7                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          walang kwenta matching nyu..
8                                                                                                                                                                                                                                                                                                                                                                                                                                     so laggy like my wifi and my data have a strong network but still lag on the game
9                                                                                                                                                                                                                                                                                                                                                                        lose streak lagi ako tang ina mo ml namatay kana tang ina mo laro mo bolok tan ina mo hayup ka gago sintosinto tarantado namatay kana hayop ka
10                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    so good this game
11                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         amazing game
12                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    i love this game🥰
13                                                                                                                                                                                                                                                                                                                                                                                                                                                                  stupid match making, always team up with stupid bot
14                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 best
15                                                                                                                                                                                                                                                                                                                                                                                                                   it has been my comfort zone whenever im bored and i also enjoy playing with my friends i love it!!
16                                                                                                                                                                                                                                                                                       my account got ban for no reason and i need it back is because simultaneous match but i didn't play with same enemy or something and all people got banned because of that so i need it back please is important to my brother
17                                                                                                                                                                                                                                                                                                                                                                                                                                                                 don't revamped luo yi, her skin is already okay!!!!!
18                                                                                                                                                                                                                                                                                                                                                                                                                                                                           constantly updating, even when in-game.👎👎👎
19                                                                                                                                                                                                                                                                                                                                                                                                      maganda naman, kaso pa legend ka na daming cancer ,may tanga may bobo may isip bata tapos ng tri-trip. yon lang
20                                                                                                                                                                                                                                                                                                                                                                                                                                                                          this game is the best game ever of my phone
21                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 good
22                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          game sampah
23                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         it is so fun
24                                                                                                                                                                                                                                                                                                                                                                       i'll make it 5 star if all the limited event skins will be for sale on every promo dias events, so that others who missed the event can buy it
25                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              me w210
26                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               so fun
27                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 good
28                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   ok
29                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        aungthihakyaw
30                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             good boy
31                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   greatest game ever
32                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              diamond
33                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  gud
34                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           this the best game overall
35                                                                                                                                                                                                                                                                                                                                         woy moonton, klau ada yg ngelaporin player yang gameplaynya kyk bot please la di kasih sanksi bukann mlh lu proses" mulu kgaa ada sanksinya, pdhl jelas" gameplaynya kek bot
36                                                                                                                                                                                                                                                                                                                                                                                                                                                                               like the game pls ban hackers fix bugs
37    ts game is fun and all but there’s one thing i really hate and i hope you guys can fix it, it’s not about the dark system or bad teammates it's about playing solo i'm literally facing enemies who are teaming up together while i'm solo queueing like seriously that’s so unfair you guys should make solo players face other solo players not full teams, when they’re teamed up they already have plans and coordination so ofc they have an advantage so pls fix ts it really ruins the solo experience 😭🙏🥀
38                                                                                                                                                                                                                                                                            this game is really great and also makes me have fun when playing it. but i once won but i didn't get a star, why can this happen? explain.. i'm back. now i'm gonna say in malay.moonton kalau kasih lawan tak paya la juga susah sangat

In [10]:
df['content_clean'].str.replace('[^\w\s]','',regex=True).head(50) 
# regex untuk menghapus tanda baca, simbol, dan karakter khusus lainnya. w untuk menghapus karakter non-kata, s untuk menghapus karakter spasi, dan ^ untuk negasi. Jadi, [^\w\s] berarti "hapus semua karakter yang bukan kata atau spasi".

<>:1: SyntaxWarning: invalid escape sequence '\w'
<>:1: SyntaxWarning: invalid escape sequence '\w'
C:\Users\USER\AppData\Local\Temp\ipykernel_23080\3117652995.py:1: SyntaxWarning: invalid escape sequence '\w'
  df['content_clean'].str.replace('[^\w\s]','',regex=True).head(50)

0                                                                                                                                                                                                                                                                                                                                                                                                       ano na moonton ayos ayos in mona mga matching mo kaya na lipat yong mga player sa hok gawa macthing
1                                                                                                                                                                                                                                                                                                                                                                                                                                                              ugly match making rather unfair match making
2                                             niceeee game but need to bring back my old hanzo skill new wasnt comfortable for brain too much bugs in game and too chares heating well pressure on game sir need to balance game ability roles plays heroes balanced counter heroes ability and frequency of mlbb challenges and animes free eventsfor various like kof heroes need bring some unique more to have fun wit  hacrr in games uncommon build of miya and somes depressed heroes to me hit hard
3                                                                                                                                                                                                                                                                                                                                                                                                                    if you play solo your teammates is trio or duo this game is so unfair for solo players
4                                                                                                                                                                                                                                                                                                                                                            moonton must fix match making because when you lose 1 its become lose streak and its hard to win the game when youre at the dark system server
5                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           pretty to play
6                                                                                                                                                                                                                                                                                                                                                                                                                    if you play solo your teammates is trio or duo this game is so unfair for solo players
7                                                                                                                                                                                                                                                                                                                                                                                                                                                                                walang kwenta matching nyu
8                                                                                                                                                                                                                                                                                                                                                                                                                         so laggy like my wifi and my data have a strong network but still lag on the game
9                                                                                                                                                                                                                                                                                                                                                            lose streak lagi ako tang ina mo ml namatay kana tang ina mo laro mo bolok tan ina mo hayup ka gago sintosinto tarantado namatay kana hayop ka
10                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        so good this game
11                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             amazing game
12                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         i love this game
13                                                                                                                                                                                                                                                                                                                                                                                                                                                       stupid match making always team up with stupid bot
14                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     best
15                                                                                                                                                                                                                                                                                                                                                                                                         it has been my comfort zone whenever im bored and i also enjoy playing with my friends i love it
16                                                                                                                                                                                                                                                                            my account got ban for no reason and i need it back is because simultaneous match but i didnt play with same enemy or something and all people got banned because of that so i need it back please is important to my brother
17                                                                                                                                                                                                                                                                                                                                                                                                                                                            dont revamped luo yi her skin is already okay
18                                                                                                                                                                                                                                                                                                                                                                                                                                                                     constantly updating even when ingame
19                                                                                                                                                                                                                                                                                                                                                                                              maganda naman kaso pa legend ka na daming cancer may tanga may bobo may isip bata tapos ng tritrip yon lang
20                                                                                                                                                                                                                                                                                                                                                                                                                                                              this game is the best game ever of my phone
21                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     good
22                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              game sampah
23                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             it is so fun
24                                                                                                                                                                                                                                                                                                                                                             ill make it 5 star if all the limited event skins will be for sale on every promo dias events so that others who missed the event can buy it
25                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  me w210
26                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   so fun
27                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     good
28                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       ok
29                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            aungthihakyaw
30                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 good boy
31                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       greatest game ever
32                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  diamond
33                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      gud
34                                                                                                                                                                                                                                                                                                                                                                                                                                                                               this the best game overall
35                                                                                                                                                                                                                                                                                                                                 woy moonton klau ada yg ngelaporin player yang gameplaynya kyk bot please la di kasih sanksi bukann mlh lu proses mulu kgaa ada sanksinya pdhl jelas gameplaynya kek bot
36                                                                                                                                                                                                                                                                                                                                                                                                                                                                   like the game pls ban hackers fix bugs
37    ts game is fun and all but theres one thing i really hate and i hope you guys can fix it its not about the dark system or bad teammates its about playing solo im literally facing enemies who are teaming up together while im solo queueing like seriously thats so unfair you guys should make solo players face other solo players not full teams when theyre teamed up they already have plans and coordination so ofc they have an advantage so pls fix ts it really ruins the solo experience
38                                                                                                                                                                                                                                                                          this game is really great and also makes me have fun when playing it but i once won but i didnt get a star why can this happen explain im back now im gonna say in malaymoonton kalau kasih lawan tak paya la juga susah sangat
39                                                                                                                                                                                                                                                                                    moonton always gives me bad teammates and always gives skin to the popular heros like gusion and miya and now doesnt always give free skins anymore just spin the wheel which you need to pay diamonds thats gambling

**Remove Punctuation**

In [11]:
df['content_clean'].str.replace('[^\w\s]','',regex=True)

<>:1: SyntaxWarning: invalid escape sequence '\w'
<>:1: SyntaxWarning: invalid escape sequence '\w'
C:\Users\USER\AppData\Local\Temp\ipykernel_23080\3208373244.py:1: SyntaxWarning: invalid escape sequence '\w'
  df['content_clean'].str.replace('[^\w\s]','',regex=True)

0                                                                                                                                                                                                                                                                                                                                                               ano na moonton ayos ayos in mona mga matching mo kaya na lipat yong mga player sa hok gawa macthing
1                                                                                                                                                                                                                                                                                                                                                                                                                      ugly match making rather unfair match making
2     niceeee game but need to bring back my old hanzo skill new wasnt comfortable for brain too much bugs in game and too chares heating well pressure on game sir need to balance game ability roles plays heroes balanced counter heroes ability and frequency of mlbb challenges and animes free eventsfor various like kof heroes need bring some unique more to have fun wit  hacrr in games uncommon build of miya and somes depressed heroes to me hit hard
3                                                                                                                                                                                                                                                                                                                                                                            if you play solo your teammates is trio or duo this game is so unfair for solo players
4                                                                                                                                                                                                                                                                                                                    moonton must fix match making because when you lose 1 its become lose streak and its hard to win the game when youre at the dark system server
                                                                                                                                                                                                                                  ...
95                                                                                                                                                                                                                                                                                                                                                                    perfect experience well even tho sometimes the matchmaking is still uncertain for some reason
96                                                                                                                                                                                                                                                                                                                                                                                                               bring back the old mayhem its sooo boring nowadays
97                                                                                                                                                                                               cada año el juego empeora mas  los emparejamientos comienzan hacer tediosos  para una clásica me toca esperar 12 minutos para que después me tengo 3 bots en mi equipo eso me hizo desistalarlo  8 años con el juego pero ya no me parece bueno me ire a wild rift
98                                                                                                                                                                                                                                                                      they change my id version now i cant play with my friends anymore and btw whenever i play on classic there will be always a dumb teammates like actually annoying cant even play it anymore
99                                                                                                                                                                                                                                                                                                                                                                                                                                                        best game
Name: content_clean, Length: 100, dtype: object

**Masukan ke dalam satu fungsi**

In [12]:
def clean_data(text,column_name):
    df['content_clean'] = df[column_name].str.lower()
    df['content_clean'] = df['content_clean'].str.replace('[^\w\s]','',regex=True)
    return df

<>:3: SyntaxWarning: invalid escape sequence '\w'
<>:3: SyntaxWarning: invalid escape sequence '\w'
C:\Users\USER\AppData\Local\Temp\ipykernel_23080\1186799193.py:3: SyntaxWarning: invalid escape sequence '\w'
  df['content_clean'] = df['content_clean'].str.replace('[^\w\s]','',regex=True)

In [13]:
df = clean_data(df, 'content')

print(df[['content', 'content_clean']])

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           content  \
0                                                                                                                                                                                                                                                                                                                                                                                              Ano na moonton ayos ayos in Mona mga matching MO Kaya na lipat Yong mga player sa hok gawa macthing
1                                                                                                                                                                                                                                                                                                                                                                                                                                                    ugly match making, rather unfair match making
2   niceeee game but need to bring back my old Hanzo skill new wasn't comfortable🤐 for brain.😼🩹 too much bugs in game🏁 and too chares heating well pressure on game sir😔. need to balance🏳️ game ability roles plays heroes🫥😶‍🌫️ balanced counter heroes ability🌠. and frequency of MLBB challenges. and animes free events🥺for various like KOF HEROES NEED BRING SOME Unique more to have fun wit. 💊🦋🐾🎩💤💯🩹🌸🛡️😸. hacrr in games uncommon build of Miya and somes depressed heroes to me hit hard.
3                                                                                                                                                                                                                                                                                                                                                                                                        if you play solo, your teammates is trio or duo. this game is so unfair for solo players!
4                                                                                                                                                                                                                                                                                                                                                Moonton must fix match making because when you lose 1 it's become lose streak and it's hard to win the game when you're at the dark system server
..                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             ...
95                                                                                                                                                                                                                                                                                                                                                                                                Perfect experience!. well even tho sometimes the matchmaking is still uncertain for some reason.
96                                                                                                                                                                                                                                                                                                                                                                                                                                              bring back the old mayhem its sooo boring nowadays
97                                                                                                                                                                                                                         cada año el juego empeora mas , los emparejamientos comienzan hacer tediosos , para una clásica me toca esperar 12 minutos para que después me tengo 3 bots en mi equipo. eso me hizo desistalarlo , 8 años con el juego pero ya no me parece bueno, me ire a wild rift
98                                                                                                                                                                                                                                                                                                    they change my id version now i cant play with my friends anymore and btw whenever i play on classic there will be always a dumb teammates like actually annoying, cant even play it anymore
99                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       best game

                                                                                                                                                                                                                                                                                                                                                                                                                                                    content_clean
0                                                                                                                                                                                                                                                                                                                                                             ano na moonton ayos ayos in mona mga matching mo kaya na lipat yong mga player sa hok gawa macthing
1                                                                                                                                                                                                                                                                                                                                                                                                                    ugly match making rather unfair match making
2   niceeee game but need to bring back my old hanzo skill new wasnt comfortable for brain too much bugs in game and too chares heating well pressure on game sir need to balance game ability roles plays heroes balanced counter heroes ability and frequency of mlbb challenges and animes free eventsfor various like kof heroes need bring some unique more to have fun wit  hacrr in games uncommon build of miya and somes depressed heroes to me hit hard
3                                                                                                                                                                                                                                                                                                                                                                          if you play solo your teammates is trio or duo this game is so unfair for solo players
4                                                                                                                                                                                                                                                                                                                  moonton must fix match making because when you lose 1 its become lose streak and its hard to win the game when youre at the dark system server
..                                                                                                                                                                                                                                                                                                                                                                                                                                                            ...
95                                                                                                                                                                                                                                                                                                                                                                  perfect experience well even tho sometimes the matchmaking is still uncertain for some reason
96                                                                                                                                                                                                                                                                                                                                                                                                             bring back the old mayhem its sooo boring nowadays
97                                                                                                                                                                                             cada año el juego empeora mas  los emparejamientos comienzan hacer tediosos  para una clásica me toca esperar 12 minutos para que después me tengo 3 bots en mi equipo eso me hizo desistalarlo  8 años con el juego pero ya no me parece bueno me ire a wild rift
98                                                                                                                                                                                                                                                                    they change my id version now i cant play with my friends anymore and btw whenever i play on classic there will be always a dumb teammates like actually annoying cant even play it anymore
99                                                                                                                                                                                                                                                                                                                                                                                                                                                      best game

[100 rows x 2 columns]

**Penggunaan library Spacy untuk text processing**

In [14]:
#import library spacy
import spacy

In [15]:
#load model spacy untuk text processing
nlp = spacy.load('en_core_web_sm')
phrase = df.loc[1, 'content_clean']
phrase

'ugly match making rather unfair match making'

In [16]:
doc = nlp(phrase)
doc

ugly match making rather unfair match making

**Tokenization**

In [17]:
[token for token in doc]

[ugly, match, making, rather, unfair, match, making]

**Lemmatization**

In [18]:
[token.lemma_ for token in doc if not token.is_stop] # menghapus stopword dan melakukan lemmatization pada kata-kata dalam frase.

['ugly', 'match', 'make', 'unfair', 'match', 'make']

**Stop Word**

In [19]:
list(nlp.Defaults.stop_words)[:10]

['been',
 'herein',
 'hence',
 'somewhere',
 'she',
 'n’t',
 'itself',
 'put',
 'have',
 'against']